export const SlotEvent = {
    ENTER_FRAME: "ENTER_FRAME",

    SPIN_CLICK: "SPIN_CLICK",
    STOP_CLICK: "STOP_CLICK",

    SERVER_SPIN_RESPONSE_RECEIVED: "SERVER_SPIN_RESPONSE_RECEIVED",
    SERVER_INIT_RESPONSE_RECEIVED: "SERVER_INIT_RESPONSE_RECEIVED",

    SLOT_STATE_CHANGED: "SLOT_STATE_CHANGED"

};